name: Build Chinese documentation

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

permissions:
  id-token: write

# 定义变量
env:
  INSTANCE: 'Writerside/hi'
  ARTIFACT: 'webHelpHI2-all.zip'
  DOCKER_VERSION: '241.16003'
  ALGOLIA_ARTIFACT: 'algolia-indexes-HI.zip'

# 任务
jobs:
  # 构建
  build:
    runs-on: ubuntu-latest
    steps:
      # 签出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 构建Writerside文档
      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      # 将构建的文档上传至当前任务的Artifacts
      - name: Save artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
            artifacts/${{ env.ALGOLIA_ARTIFACT }}
          retention-days: 7  # 保存7天

  # 验证 Writerside 是否存在错误，存在即中断流程
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Test documentation
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}

  # 部署至Cloudflare
  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    name: Deploy Cloudflare
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Unzip artifact
        run: |
          # 解压 artifacts 中的 web静态文件
          unzip -O UTF-8 -qq '${{ env.ARTIFACT }}' -d web-src

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          command: pages deploy web-src --project-name=ac-docs
